__author__ = 'antmil'

# Addresses for settings
PHASE_SHIFT_CAV_ADDRESS = 2
PHASE_SHIFT_FW_CAV_ADDRESS = 3
PHASE_SHIFT_FW_TET1_ADDRESS = 4
AMP_REF_IN_ADDRESS = 19
PHASE_REF_IN_ADDRESS = 20
LOOP_ENABLE_ADDRESS = 100
LOOP_INPUT_SELECTION_ADDRESS = 112
TUNING_ENABLE_ADDRESS = 300
NUM_STEPS_ADDRESS = 302
PHASE_OFFSET_ADDRESS = 304
MOVE_ADDRESS = 305
MOVE_UP_ADDRESS = 306
TUNING_RESET_ADDRESS = 307

# Addresses for diagnostics
ICAV_LOOPS_ADDRESS = 0
QCAV_LOOPS_ADDRESS = 1
ICONTROL_ADDRESS = 2
QCONTROL_ADDRESS = 3
IERROR_ADDRESS = 8
QERROR_ADDRESS = 9
IFW_CAV_LOOPS_ADDRESS = 14
QFW_CAV_LOOPS_ADDRESS = 15
IFW_TET1_LOOPS_ADDRESS = 16
QFW_TET1_LOOPS_ADDRESS = 17
ISPARE_ADDRESS = 24
QSPARE_ADDRESS = 25
AMP_CAV_ADDRESS = 38
AMP_FW_ADDRESS = 39
ANG_CAV_FW_ADDRESS = 40
ANG_CAV_L_ADDRESS = 41
ANG_FW_L_ADDRESS = 42
